version: 2
updates:
- package-ecosystem: bundler
  directory: /
  labels:
    - â¬†ï¸â¬‡ï¸ dependencies
  schedule:
    interval: weekly
  commit-message:
    prefix: â¬†ï¸
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: â¬†ï¸ğŸ‘·
  labels:
    - â¬†ï¸â¬‡ï¸ dependencies
