version: 2.1

default_steps: &default_steps
  steps:
    - checkout
    # For Ruby 2.2 we can't just do gem update --system, because it will pull rubygems >3.0,
    # which doesn't work on Ruby 2.2. See: https://github.com/rubygems/rubygems/issues/2534
    - run: gem i rubygems-update -v '<3' && update_rubygems
    # We need this specific version of bundler for our Gemfile. (v2 doesn't work)
    - run: gem install bundler --version '1.7'
    - run: bundle install
    - run: xvfb-run bundle exec rspec
    - run: bundle exec rubocop -D

jobs:
  ruby_latest:
    docker:
      - image: circleci/ruby:latest-node-browsers
    <<: *default_steps
  ruby_24:
    docker:
      - image: circleci/ruby:2.4-node-browsers
    <<: *default_steps
  ruby_23:
    docker:
      - image: circleci/ruby:2.3-node-browsers
    <<: *default_steps
  ruby_22:
    docker:
      - image: circleci/ruby:2.2.6-node-browsers
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - ruby_latest
      - ruby_24
      - ruby_23
      - ruby_22
